<?php
    session_start();
    if($_SESSION['ceid']=='cone')
                    {
                        $_SESSION['ceid']='ctwo';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='ctwo')
                    {
                        $_SESSION['ceid']='cthree';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='cthree')
                    {
                        $_SESSION['ceid']='cfour';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='cfour')
                    {
                        $_SESSION['ceid']='cfive';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='cfive')
                    {
                        $_SESSION['ceid']='csix';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='csix')
                    {
                        $_SESSION['ceid']='cseven';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='cseven')
                    {
                        $_SESSION['ceid']='ceight';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='ceight')
                    {
                        $_SESSION['ceid']='cnine';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='cnine')
                    {
                        $_SESSION['ceid']='cten';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['ceid']=='cten')
                    {
                        $_SESSION['ceid']='cten';
                        $id1=$_SESSION['ceid'];
                    }
                    header("location:editorial.php");
                    //header("location.href=editorial.php");
                ?>