<?php
    session_start();
    if($_SESSION['qeid']=='qone')
                    {
                        $_SESSION['qeid']='qtwo';
                        $id1=$_SESSION['qeid'];
                    }
                    elseif($_SESSION['qeid']=='qtwo')
                    {
                        $_SESSION['qeid']='qthree';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['qeid']=='qthree')
                    {
                        $_SESSION['qeid']='qfour';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['qeid']=='qfour')
                    {
                        $_SESSION['qeid']='qfive';
                        $id1=$_SESSION['ceid'];
                    }
                    elseif($_SESSION['qeid']=='qfive')
                    {
                        $_SESSION['qeid']='qsix';
                        $id1=$_SESSION['qeid'];
                    }
                    elseif($_SESSION['qeid']=='qsix')
                    {
                        $_SESSION['qeid']='qseven';
                        $id1=$_SESSION['qeid'];
                    }
                    elseif($_SESSION['qeid']=='qseven')
                    {
                        $_SESSION['qeid']='qeight';
                        $id1=$_SESSION['qeid'];
                    }
                    elseif($_SESSION['qeid']=='qeight')
                    {
                        $_SESSION['qeid']='qnine';
                        $id1=$_SESSION['qeid'];
                    }
                    elseif($_SESSION['qeid']=='qnine')
                    {
                        $_SESSION['qeid']='qten';
                        $id1=$_SESSION['qeid'];
                    }
                    elseif($_SESSION['ceid']=='cten')
                    {
                        $_SESSION['ceid']='cten';
                        $id1=$_SESSION['ceid'];
                    }
                    header("location:qeditorial.php");
                    //header("location.href=editorial.php");
                ?>