<?php
    session_start();
    if($_SESSION['veid']=='vone')
                    {
                        $_SESSION['veid']='vtwo';
                        $id1=$_SESSION['veid'];
                    }
                    elseif($_SESSION['veid']=='vtwo')
                    {
                        $_SESSION['veid']='vthree';
                        $id1=$_SESSION['veid'];
                    }
                    elseif($_SESSION['veid']=='vthree')
                    {
                        $_SESSION['veid']='vfour';
                        $id1=$_SESSION['veid'];
                    }
                    elseif($_SESSION['veid']=='vfour')
                    {
                        $_SESSION['veid']='vfive';
                        $id1=$_SESSION['veid'];
                    }
                    elseif($_SESSION['veid']=='vfive')
                    {
                        $_SESSION['veid']='vsix';
                        $id1=$_SESSION['veid'];
                    }
                    elseif($_SESSION['veid']=='vsix')
                    {
                        $_SESSION['veid']='vseven';
                        $id1=$_SESSION['veid'];
                    }
                    elseif($_SESSION['veid']=='vseven')
                    {
                        $_SESSION['veid']='vseven';
                        $id1=$_SESSION['veid'];
                    }
                    
                    header("location:veditorial.php");
                    //header("location.href=editorial.php");
                ?>